spring.application.name=assistente-financeiro

spring.datasource.url=jdbc:mysql://localhost:3306/assistente_financeiro
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.model=gemini-3.6-flash

whisper.cli.path=${WHISPER_CLI_PATH}
whisper.model.path=${WHISPER_MODEL_PATH}

piper.cli.path=${PIPER_CLI_PATH}
piper.model.path=${PIPER_MODEL_PATH}